---
# Development Node Configuration

containers:
  ubuntu2404-dev:
    ensure: present
    state: running
    image: com.ubuntu.cloud:server:24.04:amd64
    image_source: ubuntu
    image_artifact: rootfs
    profile: compat
    cloud_init:
      template: ubuntu_base
      meta_data:
        purpose: development

  ubuntu2204-test:
    ensure: present
    state: running
    image: com.ubuntu.cloud:server:22.04:amd64
    image_source: ubuntu
    image_artifact: rootfs
    profile: standard
    cloud_init:
      template: ubuntu_base
